[tool.ruff]
# Target Python 3.8+ to be compatible with older systems
target-version = "py38"

# Include source code and root-level Python files
include = ["src/**/*.py", "*.py"]

# Standard line length
line-length = 120

[tool.ruff.lint]
# Enable flake8 rules, import sorting, and common best practices
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort (import sorting)
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "SIM",  # flake8-simplify
]

# Disable specific rules that might be too strict
ignore = [
    "E501",  # Line too long (let formatter handle this)
    "B008",  # Do not perform function calls in argument defaults
    "SIM108", # Use ternary operator instead of if-else-block
]

[tool.ruff.lint.isort]
# Configure import sorting
known-first-party = ["src"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.format]
# Use double quotes for consistency
quote-style = "double"

# Respect existing line endings
line-ending = "auto"

# Format docstrings
docstring-code-format = true