version: "3"

vars:
  PI_HOST: wekker
  REMOTE_DIR: /home/wekker/deploy
  VENV_DIR: /home/wekker/deploy/venv # how to dry
  SCRIPT: main.py

includes:
  remote: ./tasks/Taskfile.remote.yml

tasks:

  run:
    desc: Run Python program on Raspberry Pi and stream logs
    cmds:
      - task: remote:deploy
      - ssh -t {{.PI_HOST}} "{{.VENV_DIR}}/bin/python3 {{.REMOTE_DIR}}/{{.SCRIPT}}"

  lint:
    desc: Run ruff linting checks
    cmds:
      - . venv/bin/activate && ruff check .

  format:
    desc: Format code with ruff
    cmds:
      - . venv/bin/activate && ruff format .

  format-check:
    desc: Check if code needs formatting (dry-run)
    cmds:
      - . venv/bin/activate && ruff format --check .

  lint-fix:
    desc: Auto-fix linting issues where possible
    cmds:
      - . venv/bin/activate && ruff check --fix .

  check:
    desc: Run all code quality checks
    cmds:
      - task: lint
      - task: format-check
