version: '3'

tasks:
  setup:
    desc: Create virtualenv and install dependencies
    cmds:
      - ssh {{.PI_HOST}} mkdir {{.REMOTE_DIR}}
      - ssh {{.PI_HOST}} "python3 -m venv -system-site-packages {{.VENV_DIR}}"
      - rsync -avz requirements.txt {{.PI_HOST}}:{{.REMOTE_DIR}}/
      - ssh {{.PI_HOST}} "{{.VENV_DIR}}/bin/pip install -r {{.REMOTE_DIR}}/requirements.txt"

  service_enable:
    desc: Enable wekker service
    cmds:
      - ssh {{.PI_HOST}} "sudo systemctl enable wekker_main.service"

  service_disable:
    desc: Disable wekker service
    cmds:
      - ssh {{.PI_HOST}} "sudo systemctl disable wekker_main.service"

  service_start:
    desc: Start wekker service
    cmds:
      - ssh {{.PI_HOST}} "sudo systemctl start wekker_main.service"

  service_stop:
    desc: Stop wekker service
    cmds:
      - ssh {{.PI_HOST}} "sudo systemctl stop wekker_main.service"

  service_status:
    desc: Get status of the wekker service
    cmds:
      - ssh {{.PI_HOST}} "systemctl status wekker_main.service"

  logs:
    desc: Get logs
    cmds:
      - ssh {{.PI_HOST}} "journalctl -u wekker_main.service -f"

  clean:
    desc: Delete project folder from Raspberry Pi
    cmds:
      - ssh {{.PI_HOST}} "rm -rf {{.REMOTE_DIR}}"

  deploy:
    desc: Upload project files to Raspberry Pi
    cmds:
      - rsync -avz --exclude '__pycache__' --exclude '.venv' ./src/ {{.PI_HOST}}:{{.REMOTE_DIR}}

  update:
    desc: Deploy new service and start it
    cmds:
      - task: service_stop
      - task: deploy
      - task: service_start
      - task: service_status
